### ISSUE TITLE
To build your own version of java_sld.jar

### ISSUE THREAD

**Issue by NeilMorris** [Lightstreamer/Lightstreamer-example-StockList-client-java#3]
I'm new to maven so this wasn't obvious to me. It may be worth including under the section, 'To build your own version of java_sld.jar...' Add the below plugin to the POM and then to build the jar with the given mvn command.

            <plugin> 
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>javasedemo.swing.StockListDemo</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
            </plugin>  

mvn clean compile assembly:single

I'm using NetBeans so after adding the plugin I select Run Maven -> Goals -> type  _clean compile assembly:single_ in Goals and click OK.

**Comment by acarioni** [comment]
Hi Neil,
You can run the demo from the command line as pointed out in the README or you can import the project in your favorite IDE and run the demo inside it. In either case you don’t need a full assembly of the demo (but you may prefer this way if you want to distribute your application).
