### ISSUE TITLE
Start Script has an error

### ISSUE THREAD

**Issue by kparmar1** [Lightstreamer/Lightstreamer-example-StockList-client-java#4]
In your release deploy.zip the shell script to start (linux/unix) is incorrect I think (unless I'm missing something).

The script start_demo.sh contains the commend:

java**w** -jar java_sld.jar http://localhost:8080 &

when it should be:

java -jar java_sld.jar http://localhost:8080 &

(javaw is for windows and windowless mode, and as it's a shell script ...)

**Comment by Bravo27** [comment]
Yes you are right, I have updated the script in the deploy.zip.
Thank you.
